from __future__ import annotations

from homeops.models import (
    EventItem,
    HomeState,
    ScenarioConfig,
    TaskItem,
    UserState,
)


def saturday_reset() -> ScenarioConfig:
    return ScenarioConfig(
        id="saturday_reset",
        title="Saturday Reset",
        description="A normal weekend household reset day with moderate backlog and one important bill deadline.",
        initial_user=UserState(
            current_time_minutes=8 * 60,
            energy=75.0,
            stress=25.0,
            satisfaction=50.0,
        ),
        initial_home=HomeState(
            cleanliness=45.0,
            clutter=55.0,
            guest_readiness=40.0,
            kitchen_readiness=50.0,
            laundry_backlog=60.0,
        ),
        tasks=[
            TaskItem(
                id="wash_dishes",
                title="Wash dishes",
                category="kitchen",
                room="kitchen",
                priority=4,
                urgency=4,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=10,
                aversion=4,
                kitchen_readiness_impact=20.0,
                cleanliness_impact=10.0,
                satisfaction_impact=5.0,
            ),
            TaskItem(
                id="fold_laundry",
                title="Fold laundry",
                category="laundry",
                room="bedroom",
                priority=3,
                urgency=2,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=8,
                aversion=3,
                laundry_backlog_impact=-25.0,
                clutter_impact=-10.0,
                satisfaction_impact=4.0,
            ),
            TaskItem(
                id="tidy_living_room",
                title="Tidy living room",
                category="cleaning",
                room="living_room",
                priority=4,
                urgency=3,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=9,
                aversion=3,
                clutter_impact=-20.0,
                guest_readiness_impact=15.0,
                satisfaction_impact=5.0,
            ),
            TaskItem(
                id="vacuum_bedroom",
                title="Vacuum bedroom",
                category="cleaning",
                room="bedroom",
                priority=3,
                urgency=2,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=11,
                aversion=4,
                cleanliness_impact=12.0,
                satisfaction_impact=3.0,
            ),
            TaskItem(
                id="water_plants",
                title="Water plants",
                category="maintenance",
                room="balcony",
                priority=2,
                urgency=1,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=4,
                aversion=1,
                satisfaction_impact=2.0,
            ),
            TaskItem(
                id="pay_electricity_bill",
                title="Pay electricity bill",
                category="admin",
                room=None,
                priority=5,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=5,
                aversion=6,
                deadline_minutes=19 * 60,
                satisfaction_impact=6.0,
                completion_bonus=0.1,
            ),
        ],
        events=[
            EventItem(
                id="electricity_bill_deadline",
                title="Electricity bill due",
                event_type="bill_cutoff",
                start_minutes=19 * 60,
                mandatory=True,
                related_task_ids=["pay_electricity_bill"],
                readiness_metric="none",
            )
        ],
    )


def guests_at_6pm() -> ScenarioConfig:
    return ScenarioConfig(
        id="guests_at_6pm",
        title="Guests at 6 PM",
        description="Guests are arriving in the evening. Some tasks matter much more than others.",
        initial_user=UserState(
            current_time_minutes=8 * 60,
            energy=65.0,
            stress=35.0,
            satisfaction=45.0,
        ),
        initial_home=HomeState(
            cleanliness=35.0,
            clutter=65.0,
            guest_readiness=25.0,
            kitchen_readiness=40.0,
            laundry_backlog=50.0,
        ),
        tasks=[
            TaskItem(
                id="clean_bathroom",
                title="Clean bathroom",
                category="guest_prep",
                room="bathroom",
                priority=5,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=14,
                aversion=8,
                guest_readiness_impact=30.0,
                cleanliness_impact=20.0,
                satisfaction_impact=6.0,
            ),
            TaskItem(
                id="clear_living_room_clutter",
                title="Clear living room clutter",
                category="guest_prep",
                room="living_room",
                priority=5,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=10,
                aversion=4,
                clutter_impact=-30.0,
                guest_readiness_impact=25.0,
                satisfaction_impact=5.0,
            ),
            TaskItem(
                id="take_out_trash",
                title="Take out trash",
                category="cleaning",
                room="kitchen",
                priority=4,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=7,
                aversion=5,
                cleanliness_impact=10.0,
                guest_readiness_impact=15.0,
                kitchen_readiness_impact=10.0,
                satisfaction_impact=3.0,
            ),
            TaskItem(
                id="wipe_kitchen_counters",
                title="Wipe kitchen counters",
                category="kitchen",
                room="kitchen",
                priority=3,
                urgency=3,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=6,
                aversion=2,
                kitchen_readiness_impact=18.0,
                guest_readiness_impact=10.0,
                cleanliness_impact=8.0,
                satisfaction_impact=2.0,
            ),
            TaskItem(
                id="fold_laundry",
                title="Fold laundry",
                category="laundry",
                room="bedroom",
                priority=2,
                urgency=2,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=8,
                aversion=3,
                laundry_backlog_impact=-20.0,
                clutter_impact=-10.0,
                satisfaction_impact=3.0,
            ),
            TaskItem(
                id="reorganize_bookshelf",
                title="Reorganize bookshelf",
                category="cleaning",
                room="living_room",
                priority=1,
                urgency=1,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=7,
                aversion=1,
                satisfaction_impact=2.0,
            ),
        ],
        events=[
            EventItem(
                id="guests_arrive",
                title="Guests arrive at 6 PM",
                event_type="guests_arrival",
                start_minutes=18 * 60,
                mandatory=True,
                related_task_ids=[
                    "clean_bathroom",
                    "clear_living_room_clutter",
                    "take_out_trash",
                    "wipe_kitchen_counters",
                ],
                readiness_metric="guest_readiness",
                readiness_threshold=75.0,
            )
        ],
    )


def overwhelmed_day() -> ScenarioConfig:
    return ScenarioConfig(
        id="overwhelmed_day",
        title="Overwhelmed Day",
        description="A low-energy day with many obligations, dependencies, tighter deadlines, and competing demands that cannot all be solved comfortably.",
        initial_user=UserState(
            current_time_minutes=8 * 60,
            energy=32.0,
            stress=62.0,
            satisfaction=30.0,
        ),
        initial_home=HomeState(
            cleanliness=35.0,
            clutter=75.0,
            guest_readiness=22.0,
            kitchen_readiness=28.0,
            laundry_backlog=80.0,
        ),
        tasks=[
            TaskItem(
                id="wash_dishes",
                title="Wash dishes",
                category="kitchen",
                room="kitchen",
                priority=4,
                urgency=4,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=11,
                aversion=4,
                kitchen_readiness_impact=16.0,
                cleanliness_impact=8.0,
                satisfaction_impact=3.0,
            ),
            TaskItem(
                id="start_laundry",
                title="Start laundry",
                category="laundry",
                room="laundry_room",
                priority=3,
                urgency=3,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=6,
                aversion=2,
                completion_bonus=0.03,
            ),
            TaskItem(
                id="fold_laundry",
                title="Fold laundry",
                category="laundry",
                room="bedroom",
                priority=3,
                urgency=3,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=9,
                aversion=4,
                dependencies=["start_laundry"],
                laundry_backlog_impact=-28.0,
                clutter_impact=-12.0,
                satisfaction_impact=3.0,
            ),
            TaskItem(
                id="restock_groceries",
                title="Restock groceries",
                category="errand",
                room=None,
                priority=4,
                urgency=4,
                mandatory=True,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=13,
                aversion=5,
                deadline_minutes=16 * 60,
                kitchen_readiness_impact=22.0,
                satisfaction_impact=4.0,
            ),
            TaskItem(
                id="pay_internet_bill",
                title="Pay internet bill",
                category="admin",
                room=None,
                priority=5,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=4,
                aversion=9,
                deadline_minutes=15 * 60 + 30,
                satisfaction_impact=7.0,
                completion_bonus=0.18,
            ),
            TaskItem(
                id="call_repair_technician",
                title="Call repair technician",
                category="admin",
                room=None,
                priority=4,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=5,
                aversion=8,
                deadline_minutes=14 * 60,
                satisfaction_impact=5.0,
                completion_bonus=0.08,
            ),
            TaskItem(
                id="prep_guest_room",
                title="Prep guest room",
                category="guest_prep",
                room="guest_room",
                priority=4,
                urgency=4,
                mandatory=True,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=12,
                aversion=6,
                deadline_minutes=18 * 60,
                guest_readiness_impact=26.0,
                clutter_impact=-15.0,
                satisfaction_impact=4.0,
            ),
            TaskItem(
                id="clear_kitchen_surfaces",
                title="Clear kitchen surfaces",
                category="kitchen",
                room="kitchen",
                priority=4,
                urgency=4,
                mandatory=False,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=8,
                aversion=3,
                kitchen_readiness_impact=16.0,
                cleanliness_impact=7.0,
                satisfaction_impact=2.0,
            ),
            TaskItem(
                id="receive_delivery",
                title="Receive delivery",
                category="errand",
                room=None,
                priority=5,
                urgency=5,
                mandatory=True,
                estimated_total_minutes=30,
                remaining_minutes=30,
                energy_cost_per_step=2,
                aversion=1,
                deadline_minutes=14 * 60 + 30,
                satisfaction_impact=3.0,
                completion_bonus=0.12,
            ),
            TaskItem(
                id="mop_floor",
                title="Mop floor",
                category="cleaning",
                room="kitchen",
                priority=2,
                urgency=2,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=14,
                aversion=6,
                cleanliness_impact=14.0,
                guest_readiness_impact=6.0,
                satisfaction_impact=2.0,
            ),
            TaskItem(
                id="organize_pantry_labels",
                title="Organize pantry labels",
                category="kitchen",
                room="kitchen",
                priority=1,
                urgency=1,
                mandatory=False,
                estimated_total_minutes=60,
                remaining_minutes=60,
                energy_cost_per_step=5,
                aversion=1,
                satisfaction_impact=2.0,
            ),
        ],
        events=[
            EventItem(
                id="repair_call_cutoff",
                title="Repair technician call before 2 PM",
                event_type="appointment",
                start_minutes=14 * 60,
                mandatory=True,
                related_task_ids=["call_repair_technician"],
                readiness_metric="none",
            ),
            EventItem(
                id="delivery_window",
                title="Delivery window 2 PM to 2:30 PM",
                event_type="delivery_window",
                start_minutes=14 * 60,
                end_minutes=14 * 60 + 30,
                mandatory=True,
                related_task_ids=["receive_delivery"],
                readiness_metric="none",
            ),
            EventItem(
                id="internet_bill_cutoff",
                title="Internet bill cutoff at 3:30 PM",
                event_type="bill_cutoff",
                start_minutes=15 * 60 + 30,
                mandatory=True,
                related_task_ids=["pay_internet_bill"],
                readiness_metric="none",
            ),
            EventItem(
                id="family_visit",
                title="Family visit at 6 PM",
                event_type="guests_arrival",
                start_minutes=18 * 60,
                mandatory=True,
                related_task_ids=["prep_guest_room", "clear_kitchen_surfaces"],
                readiness_metric="guest_readiness",
                readiness_threshold=65.0,
            ),
        ],
    )


SCENARIOS = {
    "saturday_reset": saturday_reset,
    "guests_at_6pm": guests_at_6pm,
    "overwhelmed_day": overwhelmed_day,
}
